import type { Metadata } from "next";
import Link from "next/link";
import { Compass } from "lucide-react";

export const metadata: Metadata = {
  title: "Terms of Service — Meridian",
};

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-snow">
      {/* Header */}
      <div className="bg-ink py-8">
        <div className="max-w-3xl mx-auto px-6">
          <Link href="/" className="inline-flex items-center gap-2 font-heading font-bold text-xl text-accent">
            <Compass className="h-6 w-6" />
            Meridian
          </Link>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-3xl mx-auto px-6 py-12">
        <h1 className="font-heading text-3xl font-bold text-ink mb-2">Terms of Service</h1>
        <p className="text-slate text-sm font-body mb-10">Effective date: March 21, 2026</p>

        <div className="space-y-8 font-body text-charcoal leading-relaxed text-[15px]">
          <p>
            Welcome to Meridian. By creating an account or using our services, you agree to these Terms of Service. If you do not agree, please do not use Meridian.
          </p>

          <section>
            <h2 className="font-heading text-lg font-semibold text-ink mb-3">1. About Our Service</h2>
            <p className="mb-4">
              Meridian is an AI-powered career recommendation and exploration platform. We provide informational guidance including career path suggestions, skill tasters, and mentoring conversations powered by artificial intelligence.
            </p>
            <div className="bg-accent-light rounded-lg p-5">
              <p className="text-ink text-sm">
                <strong>Important:</strong> Meridian is not a licensed career counselor, employment agency, or professional advisory service. Our recommendations are informational only and should not be treated as professional career advice. We encourage you to cross-reference our suggestions with qualified human advisors.
              </p>
            </div>
          </section>

          <section>
            <h2 className="font-heading text-lg font-semibold text-ink mb-3">2. Eligibility</h2>
            <p>You must be at least 16 years of age to use Meridian. By registering, you represent that you meet this requirement.</p>
          </section>

          <section>
            <h2 className="font-heading text-lg font-semibold text-ink mb-3">3. Your Account</h2>
            <p>
              You are responsible for maintaining the confidentiality of your account credentials. You agree to provide accurate information during registration and to keep your account information up to date. You are responsible for all activity that occurs under your account.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-lg font-semibold text-ink mb-3">4. Acceptable Use</h2>
            <p className="mb-3">You agree not to:</p>
            <ul className="list-disc pl-6 space-y-1.5">
              <li>Use the service for any unlawful purpose</li>
              <li>Attempt to gain unauthorized access to our systems or other users&apos; accounts</li>
              <li>Submit false, misleading, or deceptive information</li>
              <li>Use automated tools to scrape or extract data from the service</li>
              <li>Interfere with or disrupt the integrity or performance of the service</li>
            </ul>
          </section>

          <section>
            <h2 className="font-heading text-lg font-semibold text-ink mb-3">5. AI-Generated Content</h2>
            <p>
              Career paths, skill tasters, assessments, and other recommendations are generated by artificial intelligence. While we strive for accuracy and helpfulness, AI-generated content may contain errors, omissions, or outdated information. You should independently verify any information before making career or financial decisions based on it.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-lg font-semibold text-ink mb-3">6. Intellectual Property</h2>
            <p>
              Meridian and its original content, features, and functionality are owned by Meridian and are protected by applicable intellectual property laws. Content you submit (such as conversation messages and taster responses) remains yours, but you grant us a license to use it to provide and improve our services.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-lg font-semibold text-ink mb-3">7. Limitation of Liability</h2>
            <p className="mb-3">
              To the maximum extent permitted by law, Meridian and its team shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of income, career opportunities, or data, arising from your use of the service.
            </p>
            <p>Meridian is provided on an &ldquo;as is&rdquo; and &ldquo;as available&rdquo; basis without warranties of any kind, either express or implied.</p>
          </section>

          <section>
            <h2 className="font-heading text-lg font-semibold text-ink mb-3">8. Termination</h2>
            <p>
              We may suspend or terminate your account at our discretion if you violate these terms. You may delete your account at any time. Upon termination, your right to use the service ceases immediately.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-lg font-semibold text-ink mb-3">9. Changes to These Terms</h2>
            <p>
              We may update these terms from time to time. Continued use of the service after changes constitutes acceptance of the new terms. We will make reasonable efforts to notify users of significant changes.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-lg font-semibold text-ink mb-3">10. Governing Law</h2>
            <p>These terms are governed by the laws of the State of Arizona, United States, without regard to conflict of law provisions.</p>
          </section>

          <section>
            <h2 className="font-heading text-lg font-semibold text-ink mb-3">11. Contact</h2>
            <p>
              If you have questions about these terms, contact us at{" "}
              <a href="mailto:hello@meridian.dev" className="text-accent hover:underline">hello@meridian.dev</a>.
            </p>
          </section>
        </div>

        <hr className="border-silver my-10" />
        <p className="text-center text-slate text-xs font-body">
          Meridian &mdash; AI-Powered Career Guidance
        </p>
      </div>
    </div>
  );
}
